[lib] Fix MSVC build
.\formula_lib\private\formula.cpp(283): error C2440: 'return': cannot convert from 'initializer list' to 'formula::internal_evaluation_result'

internal_evaluation_result was not aggregate, bacause of the default initializations